### ISSUE TITLE
distributed version?

### ISSUE THREAD

**Issue by wshager** [cruppstahl/upscaledb#63]
Are there any plans to create a distributed version of upscaledb, e.g. on hdfs?

**Comment by cruppstahl** [comment]
No such plans.

Using a distributed file system will not be sufficient because some of them (i.e. hdfs) do not support random file access, and also the memory will have to be replicated as well, since transactions are not immediately stored on disk.

The other problem is that high availability usually also requires 24/7 support, which is something that i can not/do not want to offer.

That being said, you're not the first who asks and if there's really a strong need then maybe adding upscaledb support to Netflix dynomite (https://github.com/Netflix/dynomite) could be a good solution.

**Comment by wshager** [comment]
@cruppstahl sounds like a great solution.
